---
title: "Summer Project"
author: "Robert Steele, Patrick Magnusson, James Perry"
date: "July 14, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
memory.limit(size = 100000)
```

```{r}
#install.packages(c('caret','imputeR'))
library(imputeR)
library(dplyr)

Accidents0515 = read.csv('Accidents0515.csv')
Accidents0515 = Accidents0515[ , -c(16,22)]  #Removed the street numbers from the data set. I dont feel that this is relevant to anything.

wreckHour = as.character(Accidents0515$Time)
Time_of_Accident = sapply(strsplit(wreckHour,':'), function(x){
                                                                x = as.numeric(x)
                                                                x[1]+x[2]/60
                                                               }
                         )
Accidents0515 = cbind(Accidents0515,Time_of_Accident)
Accidents0515 = Accidents0515[ , -12]  #Removed old time column that is now converted to numeric as Time_of_Accident


summary(Accidents0515)
dim(Accidents0515)

hist(Accidents0515$X2nd_Road_Class)
guessImpute = Accidents0515[ , c(17,20,21,23,24,25,26,28,30)]
summary(guessImpute)
###################
#Do the modeling for Junction_Control and X2nd_Road_Class BEFORE the guess imputation

#counts by distinct values for X2nd_Road_Class
x2Counts = Accidents0515 %>% 
            group_by(Accidents0515$X2nd_Road_Class) %>% 
            summarize(count = n()) %>%
            mutate(percTotal = count / sum(count))

#Getting the total of data points for all NON missing data
Total = x2Counts$count[1] +x2Counts$count[2] +x2Counts$count[3] +x2Counts$count[4] +x2Counts$count[5] +x2Counts$count[6]
Category_choice =c(1,2,3,4,5,6)
Percentage_of_Data=
                            c(x2Counts$count[1] / Total,
                              x2Counts$count[2] / Total,
                              x2Counts$count[3] / Total,
                              x2Counts$count[4] / Total,
                              x2Counts$count[5] / Total,
                              x2Counts$count[6] / Total)
Percentagesofx2 =data.frame(Category_choice,Percentage_of_Data )
sum(ceiling(732871*Percentage_of_Data)) 

#converting all NA's to 0, as that is a classifyer when no crossroad of the accident is available. We noticed that anytime another field is present that indicates the existance of a cross streer is 0, X2nd_Road_Class was NA. We confirmed this by looking also at the street numbers for the cross street and those were 0 as well. We are 100% confident that imputing 0 is the correct value for this field
Accidents0515$X2nd_Road_Class[is.na(Accidents0515$X2nd_Road_Class)] <- 0

#Showing post imputation distibutions
x2CountsPOST = Accidents0515 %>% 
            group_by(Accidents0515$X2nd_Road_Class) %>% 
            summarize(count = n()) %>%
            mutate(percTotal = count / sum(count))
x2CountsPOST


###################


guessImputeCat = imputeR::guess(x = guessImpute[ , -9], type = 'majority' ) #Quick imputation for all categorical variables not missing more than a tiny % of overall data
guessImputeCon = imputeR::guess(x = guessImpute[ , 9], type = 'median' )    #Quick imputation for all continuous variables not missing more than a tiny % of overall data

Accidents0515 = cbind(Accidents0515, guessImputeCat)        #Binding on the newly imputed values that were categorical
Accidents0515 = cbind(Accidents0515, guessImputeCon)        #Binding on the newly imputed values that were continuous
Accidents0515 = Accidents0515[ , -c(17,20,21,23,24,25,26,28,30) ]
colnames(Accidents0515)[30] <- 'Time_of_Accident'
summary(Accidents0515)


# Write CSV in R
write.csv(Accidents0515, file = "ImputedAccident0515Data.csv")





```

```{r}
library(sqldf)
sqldf("SELECT *
      FROM Accidents0515 a
      INNER JOIN Casualties0515 c ON c.Accident_Index = a.Accident_Index
      INNER JOIN Vehicles0515 v ON v.Accident_Index = c.Accident_Index")
```

